package com.lzy.design.mapper;

import com.lzy.design.po.ProjectAudit;
import com.lzy.design.po.ProjectAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ProjectAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    long countByExample(ProjectAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int deleteByExample(ProjectAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insert(ProjectAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insertSelective(ProjectAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    List<ProjectAudit> selectByExample(ProjectAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProjectAudit record, @Param("example") ProjectAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExample(@Param("record") ProjectAudit record, @Param("example") ProjectAuditExample example);
}