package com.lzy.design.mapper;

import com.lzy.design.po.TreatiseAudit;
import com.lzy.design.po.TreatiseAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TreatiseAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    long countByExample(TreatiseAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int deleteByExample(TreatiseAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insert(TreatiseAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insertSelective(TreatiseAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    List<TreatiseAudit> selectByExample(TreatiseAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") TreatiseAudit record, @Param("example") TreatiseAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExample(@Param("record") TreatiseAudit record, @Param("example") TreatiseAuditExample example);
}