package com.lzy.design.mapper;

import com.lzy.design.po.Treatise;
import com.lzy.design.po.TreatiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TreatiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    long countByExample(TreatiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int deleteByExample(TreatiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insert(Treatise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int insertSelective(Treatise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    List<Treatise> selectByExample(TreatiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    Treatise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Treatise record, @Param("example") TreatiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByExample(@Param("record") Treatise record, @Param("example") TreatiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByPrimaryKeySelective(Treatise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatise
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    int updateByPrimaryKey(Treatise record);
}