package com.lzy.design.po;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pid
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date firstAuditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date secondAuditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pid
     *
     * @return the value of book.pid
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pid
     *
     * @param pid the value for book.pid
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.audit_status
     *
     * @return the value of book.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.audit_status
     *
     * @param auditStatus the value for book.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.first_audit_time
     *
     * @return the value of book.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getFirstAuditTime() {
        return firstAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.first_audit_time
     *
     * @param firstAuditTime the value for book.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setFirstAuditTime(Date firstAuditTime) {
        this.firstAuditTime = firstAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.second_audit_time
     *
     * @return the value of book.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getSecondAuditTime() {
        return secondAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.second_audit_time
     *
     * @param secondAuditTime the value for book.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setSecondAuditTime(Date secondAuditTime) {
        this.secondAuditTime = secondAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher
     *
     * @return the value of book.publisher
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher
     *
     * @param publisher the value for book.publisher
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.year
     *
     * @return the value of book.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.year
     *
     * @param year the value for book.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.introduction
     *
     * @return the value of book.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.introduction
     *
     * @param introduction the value for book.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}