package com.lzy.design.po;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.idcard
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.password
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonIgnore
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.email
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.degree
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.phone
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.department
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.position
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.role
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.idcard
     *
     * @return the value of person.idcard
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.idcard
     *
     * @param idcard the value for person.idcard
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.password
     *
     * @return the value of person.password
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.password
     *
     * @param password the value for person.password
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.email
     *
     * @return the value of person.email
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.email
     *
     * @param email the value for person.email
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.degree
     *
     * @return the value of person.degree
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.degree
     *
     * @param degree the value for person.degree
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.phone
     *
     * @return the value of person.phone
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.phone
     *
     * @param phone the value for person.phone
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.department
     *
     * @return the value of person.department
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.department
     *
     * @param department the value for person.department
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.position
     *
     * @return the value of person.position
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.position
     *
     * @param position the value for person.position
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.role
     *
     * @return the value of person.role
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.role
     *
     * @param role the value for person.role
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}