package com.lzy.design.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectAuditExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public ProjectAuditExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdIdIsNull() {
            addCriterion("ad_id is null");
            return (Criteria) this;
        }

        public Criteria andAdIdIsNotNull() {
            addCriterion("ad_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdIdEqualTo(Integer value) {
            addCriterion("ad_id =", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotEqualTo(Integer value) {
            addCriterion("ad_id <>", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdGreaterThan(Integer value) {
            addCriterion("ad_id >", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ad_id >=", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdLessThan(Integer value) {
            addCriterion("ad_id <", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdLessThanOrEqualTo(Integer value) {
            addCriterion("ad_id <=", value, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdIn(List<Integer> values) {
            addCriterion("ad_id in", values, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotIn(List<Integer> values) {
            addCriterion("ad_id not in", values, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdBetween(Integer value1, Integer value2) {
            addCriterion("ad_id between", value1, value2, "adId");
            return (Criteria) this;
        }

        public Criteria andAdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ad_id not between", value1, value2, "adId");
            return (Criteria) this;
        }

        public Criteria andPjIdIsNull() {
            addCriterion("pj_id is null");
            return (Criteria) this;
        }

        public Criteria andPjIdIsNotNull() {
            addCriterion("pj_id is not null");
            return (Criteria) this;
        }

        public Criteria andPjIdEqualTo(Integer value) {
            addCriterion("pj_id =", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdNotEqualTo(Integer value) {
            addCriterion("pj_id <>", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdGreaterThan(Integer value) {
            addCriterion("pj_id >", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pj_id >=", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdLessThan(Integer value) {
            addCriterion("pj_id <", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdLessThanOrEqualTo(Integer value) {
            addCriterion("pj_id <=", value, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdIn(List<Integer> values) {
            addCriterion("pj_id in", values, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdNotIn(List<Integer> values) {
            addCriterion("pj_id not in", values, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdBetween(Integer value1, Integer value2) {
            addCriterion("pj_id between", value1, value2, "pjId");
            return (Criteria) this;
        }

        public Criteria andPjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pj_id not between", value1, value2, "pjId");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonIsNull() {
            addCriterion("audit_opinion_reason is null");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonIsNotNull() {
            addCriterion("audit_opinion_reason is not null");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonEqualTo(String value) {
            addCriterion("audit_opinion_reason =", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonNotEqualTo(String value) {
            addCriterion("audit_opinion_reason <>", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonGreaterThan(String value) {
            addCriterion("audit_opinion_reason >", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonGreaterThanOrEqualTo(String value) {
            addCriterion("audit_opinion_reason >=", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonLessThan(String value) {
            addCriterion("audit_opinion_reason <", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonLessThanOrEqualTo(String value) {
            addCriterion("audit_opinion_reason <=", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonLike(String value) {
            addCriterion("audit_opinion_reason like", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonNotLike(String value) {
            addCriterion("audit_opinion_reason not like", value, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonIn(List<String> values) {
            addCriterion("audit_opinion_reason in", values, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonNotIn(List<String> values) {
            addCriterion("audit_opinion_reason not in", values, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonBetween(String value1, String value2) {
            addCriterion("audit_opinion_reason between", value1, value2, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionReasonNotBetween(String value1, String value2) {
            addCriterion("audit_opinion_reason not between", value1, value2, "auditOpinionReason");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionIsNull() {
            addCriterion("audit_opinion is null");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionIsNotNull() {
            addCriterion("audit_opinion is not null");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionEqualTo(Integer value) {
            addCriterion("audit_opinion =", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionNotEqualTo(Integer value) {
            addCriterion("audit_opinion <>", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionGreaterThan(Integer value) {
            addCriterion("audit_opinion >", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_opinion >=", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionLessThan(Integer value) {
            addCriterion("audit_opinion <", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionLessThanOrEqualTo(Integer value) {
            addCriterion("audit_opinion <=", value, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionIn(List<Integer> values) {
            addCriterion("audit_opinion in", values, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionNotIn(List<Integer> values) {
            addCriterion("audit_opinion not in", values, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionBetween(Integer value1, Integer value2) {
            addCriterion("audit_opinion between", value1, value2, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditOpinionNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_opinion not between", value1, value2, "auditOpinion");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_audit
     *
     * @mbg.generated do_not_delete_during_merge Mon May 18 16:32:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_audit
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}