package com.lzy.design.po;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Treatise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.p_id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date firstAuditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date secondAuditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.level
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.type
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.subject
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treatise.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.id
     *
     * @return the value of treatise.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.id
     *
     * @param id the value for treatise.id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.p_id
     *
     * @return the value of treatise.p_id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.p_id
     *
     * @param pId the value for treatise.p_id
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.title
     *
     * @return the value of treatise.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.title
     *
     * @param title the value for treatise.title
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.audit_status
     *
     * @return the value of treatise.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.audit_status
     *
     * @param auditStatus the value for treatise.audit_status
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.create_time
     *
     * @return the value of treatise.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.create_time
     *
     * @param createTime the value for treatise.create_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.update_time
     *
     * @return the value of treatise.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.update_time
     *
     * @param updateTime the value for treatise.update_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.first_audit_time
     *
     * @return the value of treatise.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getFirstAuditTime() {
        return firstAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.first_audit_time
     *
     * @param firstAuditTime the value for treatise.first_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setFirstAuditTime(Date firstAuditTime) {
        this.firstAuditTime = firstAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.second_audit_time
     *
     * @return the value of treatise.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public Date getSecondAuditTime() {
        return secondAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.second_audit_time
     *
     * @param secondAuditTime the value for treatise.second_audit_time
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setSecondAuditTime(Date secondAuditTime) {
        this.secondAuditTime = secondAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.level
     *
     * @return the value of treatise.level
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.level
     *
     * @param level the value for treatise.level
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.type
     *
     * @return the value of treatise.type
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.type
     *
     * @param type the value for treatise.type
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.subject
     *
     * @return the value of treatise.subject
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.subject
     *
     * @param subject the value for treatise.subject
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.year
     *
     * @return the value of treatise.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.year
     *
     * @param year the value for treatise.year
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treatise.introduction
     *
     * @return the value of treatise.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treatise.introduction
     *
     * @param introduction the value for treatise.introduction
     *
     * @mbg.generated Mon May 18 16:32:01 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}